name: CD

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [penxle.com, penxle.io, help.penxle.com, landing.penxle.com]
    concurrency: ${{ matrix.project }}-pr-${{ github.event.number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare local actions
        run: pnpm run build:actions

      - name: Check changes
        id: check_changes
        uses: ./actions/check-changes
        with:
          project: ${{ matrix.project }}

      - name: Build local dependencies
        if: steps.check_changes.outputs.changed == 'true'
        run: pnpm run build:deps

      - uses: dopplerhq/secrets-fetch-action@v1.1.2
        if: steps.check_changes.outputs.changed == 'true'
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          doppler-project: penxle
          doppler-config: preview
          inject-env-vars: true

      - name: Build project
        if: steps.check_changes.outputs.changed == 'true'
        run: pnpm exec turbo run build --filter=${{ matrix.project }}

      - name: Upload lambda function
        if: steps.check_changes.outputs.changed == 'true'
        uses: ./actions/upload-lambda
        with:
          project: ${{ matrix.project }}
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Pulumi
        if: steps.check_changes.outputs.changed == 'true'
        uses: pulumi/actions@v4

      - name: Deploy infrastructure
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cd infra/${{ matrix.project }}
          pulumi stack select penxle/pr-${{ github.event.number }} || pulumi stack init penxle/pr-${{ github.event.number }}
          pulumi config set aws:defaultTags '{"tags":{"ManagedBy":"Pulumi"}}'
          pulumi up --skip-preview --stack penxle/pr-${{ github.event.number }}
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
